### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by alexisduque** [Rtone/sigfox-rest-client#1]
If we want to start open source projects, I suggest we first define the copyright, patent grant, and code distribution policy, and then pick the appropriate license.

A common choice, if we want a *permissive* license that allows commercial use, grants patent to contributors, keeps copyright and tracks modifications is the [Apache License 2.0](https://choosealicense.com/licenses/apache-2.0/).

**Comment by Hany-Benz** [comment]
I totally agree with you, in fact, for this type of project, the idea is to allow users the freedom to use this SDK for any purpose, including commercial use, we will be releasing the sdk on the mvn repository.

I think that [Apache License V2.0](http://www.apache.org/licenses/LICENSE-2.0) is good choice which corresponds most closely to our needs.

**Comment by alexisduque** [comment]
So let's go ahead 😉  
We should add a LICENSE file in the repo root and put the license header in every file. 
I suggest we automate the process taking advantage of the [maven license plugin](http://www.mojohaus.org/license-maven-plugin/usage.html).

**Comment by Hany-Benz** [comment]
That's what am doing, I've just finished to do this, and created a Pull request about this ( you can have a look).

Though, I've used the Intellij copyright profile generator, it works great.
